set CPUTAPID 0x0bc11477
set CHIPNAME efm32hg309

source [find interface/stlink-v2.cfg]
source [find target/efm32.cfg]

## did not yet manage to make a working setup using srst
##reset_config srst_only
#reset_config  srst_nogate

#adapter_nsrst_delay 100
#adapter_nsrst_assert_width 100

init
targets
reset halt

# This flashes the program in "program.bin".
program program.bin verify
reset
shutdown
